service: about-bvmites-hook

provider:
  name: aws
  runtime: nodejs6.10
  profile: bvmites
  memorySize: 128
  versionFunctions: false

functions:
  organization:
    handler: handler.organization
    events:
      - http: POST organization
